apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: cc-adapter
spec:
  template:
    serviceAccountName: argo-workflows-server
  dependencies:
    - name: webhook-dep
      eventSourceName: cc-adapter
      eventName: cc-adapter
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: cc-adapter
              spec:
                arguments:
                  parameters:
                  - name: file
                    value: __TO_BE_REPLACD__
                workflowTemplateRef:
                  name: cc-adapter
          parameters:
            - src:
                dependencyName: webhook-dep
                dataKey: body.Records.0.s3.object.key
              dest: spec.arguments.parameters.0.value