apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cc-adapter
spec:
  arguments:
    parameters:
      - name: file
  templates:
    - name: entry
      dag:
        tasks:
        - name: xls2csv
          template: xls2csv
        - name: cleanup
          template: cleanup-csv
          dependencies: [xls2csv]
          arguments:
            artifacts:
            - name: in
              from: "{{tasks.xls2csv.outputs.artifacts.csv}}"
    - name: xls2csv
      inputs:
        artifacts:
        - name: file
          path: /input.xls
          s3:
            insecure: true
            key: "{{workflow.parameters.file}}"
            endpoint: rook-ceph-rgw-my-store.rook-ceph.svc:80
            bucket: argo-uploads-ec28f1b8-f2a8-4b6a-9e84-720afbe8185b
            accessKeySecret:
              name: argo-uploads
              key: AWS_ACCESS_KEY_ID
            secretKeySecret:
              name: argo-uploads
              key: AWS_SECRET_ACCESS_KEY
      outputs:
        artifacts:
        - name: csv
          path: /out.csv
      script:
        image: docker.io/sanrep/gnumeric
        command: 
        - ssconvert
        - /input.xls
        - /out.csv
    - name: cleanup-csv
      inputs:
        artifacts:
        - name: in
          path: /input.csv
      outputs:
        artifacts:
        - name: out
          path: /out.csv
      script:
        image: alpine
        command: [sh]
        workingDir: /
        source: |
          </input.csv tac | sed '1,/^,,,,,,,$/!d' | grep -v ,,,,,,, | tac > /out.csv
  entrypoint: entry
  serviceAccountName: git-sync
  ttlStrategy:
    secondsAfterCompletion: 3600
  podGC:
    strategy: OnPodCompletion