apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://github.com/argoproj-labs/argocd-image-updater/manifests/base

images:
- name: quay.io/argoprojlabs/argocd-image-updater
  newName: cr.local.ongy.net/argoprojlabs/argocd-image-updater
