apiVersion: v1
kind: ConfigMap
metadata:
  name: omada-ca-cert
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDSTCCAjGgAwIBAgIQH1RgnDZKm29CZ7h7YxfJizANBgkqhkiG9w0BAQsFADAo
    MSYwJAYDVQQDEx1vbWFkYS5vbWFkYS5zdmMuY2x1c3Rlci5sb2NhbDAeFw0yNjA4
    MjYwODI1MjNaFw0yNjExMjQwODI1MjNaMCgxJjAkBgNVBAMTHW9tYWRhLm9tYWRh
    LnN2Yy5jbHVzdGVyLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAsUEJolYrCB6RYfHVBBp8xZf9dptsfyVcqZ/N3YuH66Xh5GvKaEA5ctTDn5fw
    px9SiTvjpOZAo4qoSEy54NBQA7oO9UH+vFtd/s1+OscxwFXQ5fY2CXKLNDfUaxfS
    90IJLmvnijzMsdlDRuPn/2Hx2VmLRytkTx7NSWscBwQreRAl3+1LdlQ4q83dCbsC
    bbMjaYG8BD+kxzmhV2iBir0nwk3v9IzCN2sGPJIZnGUIdHTCjcIJqgJVDwDBrfw4
    J3HOwYyTDVPjRIuwU/lpU7UfpxpgJQ7jaDT3xHEcVzUs89VxUIFJX5bsIxaW9q7P
    WMd3rar/SWeQ9c/qyJXItiyekQIDAQABo28wbTAOBgNVHQ8BAf8EBAMCBaAwDAYD
    VR0TAQH/BAIwADBNBgNVHREERjBEgh1vbWFkYS5vbWFkYS5zdmMuY2x1c3Rlci5s
    b2NhbIIPb21hZGEub21hZGEuc3ZjggtvbWFkYS5vbWFkYYIFb21hZGEwDQYJKoZI
    hvcNAQELBQADggEBAEwxBeWf2vaWKzOr/hsWja9twaEhfztrSC2/M0LTmOe+qdjF
    wo2c2uV0VRNQbrwRIzyraMbRMiSrQLWsAIezT3112OeHgUd+QMJfGWmHQm0J+ouZ
    1O6lHAVYKpfMwUU0r3lnV2mrsAO9adtEkFDgAw93L6eigNuIAEqMSoErSxGVgLTo
    sDHNt7RwQzOAmNwaUk71DqHp7ppnSkFqch+rYdlE9F2Kvtk3vGsgdb3jCcIZfx+I
    JTrX+RfHmdVegS3TxZmYisFB1CmUA/Q0fkJNQ8Tw4eGXUH7pHQweBSSGl4taO31p
    KHQD56lt6ce51Sc3zh7qf6XPSOsZpdcQXsHvRJU=
    -----END CERTIFICATE-----
