apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: omada-cert
spec:
  commonName: 'omada.local.ongy.net'
  dnsNames:
  - 'omada.local.ongy.net'
  issuerRef:
    kind: ClusterIssuer
    name: luadns-lexicon
  secretName: omada-tls
