apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      resources:
        limits:
          memory: "1024Mi"
      volumes:
        - name: psql-tls-secrets
          secret:
            defaultMode: 416
            optional: true
            secretName: psql-client-secret
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v1.10.2
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1003
            runAsGroup: 1003
            privileged: false
          name: shell-operator
          env:
            - name: DB_ENGINE
              value: postgres
            - name: POSTGRES_URL_OVERRIDE
              value: postgresql://mealie@psql.psql/mealie?sslmode=verify-full&sslcert=%2Fpsql-tls-secrets%2Ftls.crt&sslkey=%2Fpsql-tls-secrets%2Ftls.key&sslrootcert=%2Fpsql-tls-secrets%2Fca.crt
            - name: BASE_URL
              value: https://mealie.local.ongy.net
            - name: MAX_WORKERS
              value: "1"
            - name: WEB_CONCURRENCY
              value: "1"
            - name: TZ
              value: Europe/Berlin
          volumeMounts:
            - mountPath: "/psql-tls-secrets"
              name: psql-tls-secrets
---

