apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-events-frontend
spec:
  templates:
    - name: entry
      dag:
        tasks:
        - name: build
          template: build
        - name: push-arm64
          dependencies: [build]
          template: push
          arguments:
            parameters:
            - name: arch
              value: arm64
            artifacts:
            - name: events-admin-dist
              from: "{{tasks.build.outputs.artifacts.events-admin-dist}}"
        - name: push-amd64
          dependencies: [build]
          template: push
          arguments:
            parameters:
            - name: arch
              value: amd64
            artifacts:
            - name: events-admin-dist
              from: "{{tasks.build.outputs.artifacts.events-admin-dist}}"
        - name: manifest-tool
          dependencies: [push-arm64, push-amd64]
          template: manifest-tool
    - name: build
      inputs:
        artifacts:
          - name: argo-source
            path: /src
            git:
              repo: https://git.local.ongy.net/ongy/events-frontend.git
              revision: "{{workflow.parameters.rev}}"
      outputs:
        artifacts:
        - name: events-admin-dist
          path: /src/events-admin/dist/events-admin
      container:
        name: main
        image: node:24-alpine
        command:
          - sh
        args:
          - -x
          - -euc
          - |
            npm install
            npm run build
            cp default.conf Dockerfile dist/events-admin
        workingDir: /src/events-admin
    - name: push
      inputs:
        artifacts:
          - name: events-admin-dist
            path: /src
        parameters:
          - name: arch
      container:
        name: main
        image: gcr.io/kaniko-project/executor
        args:
        - --custom-platform=linux/{{inputs.parameters.arch}}
        - "--dockerfile=/Dockerfile"
        - "--context=dir:///src"
        - "--destination=cr.local.ongy.net/ongy/events-frontend:{{workflow.parameters.rev}}-{{inputs.parameters.arch}}"
    - name: manifest-tool
      container:
        name: main
        image: mplatform/manifest-tool:alpine
        args:
        - push
        - from-args
        - --platforms
        - linux/amd64,linux/arm64
        - --template
        - cr.local.ongy.net/ongy/events-frontend:{{workflow.parameters.rev}}-ARCH
        - --target
        - cr.local.ongy.net/ongy/events-frontend:{{workflow.parameters.rev}}

  entrypoint: entry
  volumes:
  - name: git-ssh-key
    secret:
      secretName: gogs-deploy-key
  arguments:
    parameters:
      - name: rev
  serviceAccountName: event-aggregator
  ttlStrategy:
    secondsAfterCompletion: 3600
