apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-events-frontend
spec:
  templates:
    - name: entry
      dag:
        tasks:
        - name: build
          template: build
        - name: push
          dependencies: [build]
          template: push
          arguments:
            artifacts:
            - name: events-admin-dist
              from: "{{tasks.build.outputs.artifacts.events-admin-dist}}"

    - name: build
      inputs:
        artifacts:
          - name: argo-source
            path: /src
            git:
              repo: https://git.local.ongy.net/ongy/events-frontend.git
              revision: "{{workflow.parameters.rev}}"
      outputs:
        artifacts:
        - name: events-admin-dist
          path: /src/events-admin/dist/events-admin
      container:
        name: main
        image: node:24-alpine
        command:
          - sh
        args:
          - -x
          - -euc
          - |
            npm install
            npm run build
            cp default.conf Dockerfile dist/events-admin
        workingDir: /src/events-admin
    - name: push
      inputs:
        artifacts:
          - name: events-admin-dist
            path: /src
      container:
        name: main
        image: gcr.io/kaniko-project/executor
        args:
        - --custom-platform=linux/amd64,linux/arm64
        - "--dockerfile=/Dockerfile"
        - "--context=dir:///src"
        - "--destination=cr.local.ongy.net/ongy/events-frontend:{{workflow.parameters.rev}}"
  entrypoint: entry
  volumes:
  - name: git-ssh-key
    secret:
      secretName: gogs-deploy-key
  arguments:
    parameters:
      - name: rev
  serviceAccountName: event-aggregator
  ttlStrategy:
    secondsAfterCompletion: 3600
