apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: event-aggregator
spec:
  template:
    serviceAccountName: argo-workflows-server
  dependencies:
    - name: webhook-dep
      eventSourceName: event-aggregator
      eventName: event-aggregator
      filters:
        exprs:
          - expr: type == "tag"
            fields:
              - name: type
                path: body.ref_type
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: event-aggregator-
              spec:
                arguments:
                  parameters:
                  - name: rev
                    value: __TO_BE_REPLACD__
                workflowTemplateRef:
                  name: build-event-aggregator
          parameters:
            - src:
                dependencyName: webhook-dep
                dataKey: body.ref
              dest: spec.arguments.parameters.0.value
