apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: psql-selfsigned-ca
  namespace: cert-manager
spec:
  commonName: psql-selfsigned-ca
  duration: 87600h0m0s
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: psql-root-secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: psql-ca-issuer
spec:
  ca:
    secretName: psql-root-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: psql-server-secret
  namespace: psql
spec:
  isCA: true
  duration: 8760h # 1 years
  commonName: psql.psql
  dnsNames: ["psql.psql", "psql.psql.svc.cluster.local"]
  secretName: psql-server-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: psql-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io