apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vaultwarden
  name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      securityContext:
        sysctls:
        - name: "net.ipv4.ip_unprivileged_port_start"
          value: "80"
      volumes:
      - name: data
        nfs:
          path: /srv/share/backed/appdata/vaultwarden
          server: mario.local.ongy.net
          readOnly: false
      containers:
      - name: vaultwarden
        volumeMounts:
        - name: data
          mountPath: "/data"
        resources:
          requests:
            memory: "25Mi"
          limits:
            memory: "25Mi"
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: [ALL]
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          privileged: false
        image: vaultwarden/server:latest
        workingDir: /

