apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-tracker
  labels:
    app: tea-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tea-tracker
  template:
    metadata:
      labels:
        app: tea-tracker
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: tea-tracker-data
      - name: psql-tls-secrets
        secret:
          defaultMode: 416
          optional: true
          secretName: psql-client-secret
      containers:
      - name: tea-tracker
        image: cr.local.ongy.net/ongy/tea-tracker:v0.0.3
        ports:
        - containerPort: 3000
        env:
        - name: TEA_TRACKER_DATA
          value: /data
        - name: TEA_TRACKER_DATABASE_URL
          value: postgresql://tea-tracker:@psql.psql/tea-tracker?sslmode=verify-full&sslcert=%2Fpsql-tls-secrets%2Ftls.crt&sslkey=%2Fpsql-tls-secrets%2Ftls.key&sslrootcert=%2Fpsql-tls-secrets%2Fca.crt
        volumeMounts:
        - name: data
          mountPath: /data
        - mountPath: "/psql-tls-secrets"
          name: psql-tls-secrets
