apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - birdo
                      - mario
      automountServiceAccountToken: false
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-config
        - name: media
          persistentVolumeClaim:
            claimName: homeassistant-media
        - name: psql-tls-secrets
          secret:
            defaultMode: 416
            optional: true
            secretName: psql-client-secret
      containers:
        - image: ghcr.io/home-assistant/home-assistant
          readinessProbe:
            httpGet:
              path: /manifest.json
              port: 8123
          name: homeassistant
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: "/media"
              name: media
            - mountPath: "/psql-tls-secrets"
              name: psql-tls-secrets
---