apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 0
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - birdo
                      - mario
      automountServiceAccountToken: false
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homeassistant-config
        - name: psql-tls-secrets
          secret:
            defaultMode: 416
            optional: true
            secretName: psql-client-secret
      containers:
        - image: ghcr.io/home-assistant/home-assistant
          readinessProbe:
            httpGet:
              path: /manifest.json
              port: 8123
          name: homeassistant
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: "/psql-tls-secrets"
              name: psql-tls-secrets
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: copy
        image: alpine
        command:
        - sleep
        - infinity
        volumeMounts:
          - mountPath: "/nfs"
            name: nfs
          - mountPath: "/ceph"
            name: ceph
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: homeassistant-config-pvc
        - name: ceph
          persistentVolumeClaim:
            claimName: homeassistant-config
      restartPolicy: Never
