apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
      name: http
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: homeassistant
  namespace: default
spec:
  gateways: [istio-system/gateway]
  hosts: [homeassistant.local.ongy.net]
  http:
  - route:
    - destination:
        host: homeassistant.homeassistant.svc.cluster.local