apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-migrate-data
spec:
  template:
    spec:
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data
          readOnly: false
      - name: keycloak-data-migrate
        persistentVolumeClaim:
          claimName: keycloak-data-migrate
          readOnly: false
      containers:
      - name: copy
        image: ogivuk/rsync
        args:
        - -avhP
        - /old/
        - /new/
        volumeMounts:
        - name: keycloak-data
          mountPath: /old
        - name: keycloak-data-migrate
          mountPath: /new
      restartPolicy: Never
