apiVersion: v1
kind: ConfigMap
metadata:
  name: supervisord-config
  namespace: mediaserver
data:
  supervisord.conf: |-
    [supervisord]
    nodaemon=true                ; start in foreground if true; default false
    logfile=/dev/stdout          ; main log file; default $CWD/supervisord.log
    pidfile=/tmp/supervisord.pid ; supervisord pidfile; default supervisord.pid
    logfile_maxbytes=0           ; max main logfile bytes b4 rotation; default 50MB
    logfile_backups=0            ; # of main logfile backups; 0 means none, default 10
    loglevel=info                ; log level; default info; others: debug,warn,trace
    user=paperless

    [program:gunicorn]
    command=gunicorn -c /usr/src/paperless/gunicorn.conf.py paperless.asgi:application
    user=paperless
    priority = 1
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    [program:consumer]
    command=python3 manage.py document_consumer
    user=paperless
    stopsignal=INT
    priority = 20
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    [program:celery]

    command = celery --app paperless worker --loglevel INFO
    user=paperless
    stopasgroup = true
    stopwaitsecs = 60
    priority = 5
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    [program:celery-beat]

    command = celery --app paperless beat --loglevel INFO
    user=paperless
    stopasgroup = true
    priority = 10
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    [program:celery-flower]
    command = /usr/local/bin/flower-conditional.sh
    user = paperless
    startsecs = 0
    priority = 40
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0