apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paperless-core
  name: paperless-core
  namespace: mediaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-core
  template:
    metadata:
      labels:
        app: paperless-core
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - paperless-broker
              topologyKey: kubernetes.io/hostname
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - paperless-proxy
              topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data
            readOnly: false
        - name: supervisord-config
          configMap:
            name: supervisord-config
        - name: tmp-dir
          emptyDir:
            medium: Memory
            sizeLimit: 500Mi
        - name: var-log
          emptyDir:
            medium: Memory
            sizeLimit: 500Mi
        - name: paperless-export
          nfs:
            path: /srv/share/backed/appdata/paperless/export
            server: mario.local.ongy.net
            readOnly: false
        - name: paperless-consume
          nfs:
            path: /srv/share/backed/appdata/paperless/consume
            server: mario.local.ongy.net
            readOnly: false
        - name: psql-tls-secrets
          secret:
            secretName: psql-client-secret
            optional: false
            defaultMode: 0640
      containers:
        - image: dockurr/samba
          env:
            - name: PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: smbcreds
          imagePullPolicy: Always
          name: consume-loop
          command: [sh]
          args:
            - -eux
            - -c
            - |
              DB="/data/.consumed.txt"
              touch "${DB}"

              consume() {
                cd /consume
                for file in $(smbclient  //192.168.3.200/USBSTORAGE -NU ongy%$PASS -c 'cd EPSCAN\001; mask *.PDF; ls' | grep -oE "EPSON.*.PDF"); do
                  if grep -q "${file}" "${DB}"; then continue; fi
                  smbclient //192.168.3.200/USBSTORAGE -NU ongy%$PASS -c "cd EPSCAN\001; get ${file}"
                  #cp "${file}" /consume
                  echo "${file}" >> "${DB}"
                  echo Processed file "${file}"
                done
              }

              consume
              # Doing it like this makes it easier to stop the process via signal!
              while sleep 1800 ; do
                consume
              done
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            privileged: false
          volumeMounts:
            - mountPath: "/consume"
              name: paperless-consume
              readOnly: false
            - mountPath: "/data"
              subPath: data
              name: paperless-data
        - image: ghcr.io/paperless-ngx/paperless-ngx
          command: ['/usr/local/bin/supervisord']
          args:
            - -c
            - /etc/supervisord.conf
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            privileged: false
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              httpHeaders:
                - name: Host
                  value: paperless.local.ongy.net
          env:
            - name: PAPERLESS_AUTO_LOGIN_USERNAME
              value: admin
            - name: PAPERLESS_DBHOST
              value: "psql.psql"
            - name: PAPERLESS_REDIS
              value: "redis://paperless-broker:6379"
            - name: PAPERLESS_DBSSLMODE
              value: "verify-ca"
            - name: PAPERLESS_DBSSLROOTCERT
              value: "/psql-tls-secrets/..data/ca.crt"
            - name: PAPERLESS_DBSSLCERT
              value: "/psql-tls-secrets/..data/tls.crt"
            - name: PAPERLESS_DBSSLKEY
              value: "/psql-tls-secrets/..data/tls.key"
            - name: PAPERLESS_TIME_ZONE
              value: "Europe/Berlin"
            - name: PAPERLESS_ADMIN_USER
              value: "admin"
            - name: PAPERLESS_ADMIN_PASSWORD
              value: "password"
            - name: PAPERLESS_URL
              value: https://paperless.local.ongy.net
          name: core
          volumeMounts:
            - mountPath: "/etc/supervisord.conf"
              name: supervisord-config
              subPath: supervisord.conf
            - mountPath: "/tmp/"
              name: tmp-dir
            - mountPath: "/var/log/supervisord"
              name: var-log
            - mountPath: "/usr/src/paperless/data"
              name: paperless-data
              subPath: data
            - mountPath: "/usr/src/paperless/media"
              name: paperless-data
              subPath: media
            - mountPath: "/usr/src/paperless/export"
              name: paperless-export
            - mountPath: "/usr/src/paperless/consume"
              name: paperless-consume
            - name: psql-tls-secrets
              mountPath: "/psql-tls-secrets"
              readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paperless-broker
  name: paperless-broker
  namespace: mediaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-broker
  template:
    metadata:
      labels:
        app: paperless-broker
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - paperless-core
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: redis-data
          nfs:
            path: /srv/share/backed/appdata/paperless/redis
            server: mario.local.ongy.net
            readOnly: false
      containers:
        - image: docker.io/library/redis:7
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 1000
            privileged: false
          name: paperless-broker
          volumeMounts:
            - mountPath: "/data"
              name: redis-data
