apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paperless-proxy
  name: paperless-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-proxy
  template:
    metadata:
      labels:
        app: paperless-proxy
    spec:
      containers:
        - image: quay.io/oauth2-proxy/oauth2-proxy
          args:
            - --provider=keycloak-oidc
            - --client-id=paperless
            - --client-secret=tdhUCZ3hwutrmqcBQaSGMUSAg3jNXeh2
            - --redirect-url=https://paperless.local.ongy.net/oauth2/callback
            - --oidc-issuer-url=https://keycloak.local.ongy.net/realms/local.ongy.net
            - --code-challenge-method=S256
            - --reverse-proxy=true
            - --http-address=0.0.0.0:8080
            - --upstream=http://paperless-core
            - --email-domain=*
            - --cookie-secret=QjFoZ3QwN2JHQUtYeGs2S2hmQU9TbCtVUWh0NlJVWXc=
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 1000
            privileged: false
          name: paperless-proxy
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: paperless-proxy
  namespace: mediaserver
spec:
  podSelector:
    matchLabels:
      app: paperless-proxy
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.128.2/32
      ports:
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app: paperless-core
      ports:
        - protocol: TCP
          port: 80
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: paperless-proxy
  namespace: mediaserver
spec:
  endpointSelector:
    matchLabels:
      app: paperless-proxy
  ingress:
    - fromEntities:
        - ingress
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-oauth
  namespace: mediaserver
spec:
  selector:
    app: paperless-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: paperless
spec:
  hostnames:
    - paperless.local.ongy.net
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: paperless-oauth
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
