apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr
  labels:
    ongy.net/keycloak-application: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr-proxy
  name: radarr-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr-proxy
  template:
    metadata:
      labels:
        app: radarr-proxy
    spec:
      containers:
        - image: quay.io/oauth2-proxy/oauth2-proxy
          args:
          - --provider=keycloak-oidc
          - --redirect-url=https://radarr.local.ongy.net/oauth2/callback
          - --oidc-issuer-url=https://keycloak.local.ongy.net/realms/local.ongy.net
          - --code-challenge-method=S256
          - --reverse-proxy=true
          - --http-address=0.0.0.0:8080
          - --upstream=http://radarr
          - --email-domain=*
          - --cookie-secret=QjFoZ3QwN2JHQUtYeGs2S2hmQU9TbCtVUWh0NlJVWXc=

          - --skip-provider-button=true
          env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: radarr-client-ceph
                key: client_id
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: radarr-client-ceph
                key: client_secret
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 1000
            privileged: false
          name: oauth-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-proxy
spec:
  selector:
    app: radarr-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http