apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shell-operator
  name: shell-operator
  namespace: shell-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell-operator
  template:
    metadata:
      labels:
        app: shell-operator
    spec:
      volumes:
        - name: hooks
          configMap:
            defaultMode: 0555
            name: hooks
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 150Mi
        - name: var-run
          emptyDir:
            medium: Memory
            sizeLimit: 150Mi
        - name: ansible
          emptyDir:
            medium: Memory
            sizeLimit: 100Mi
      containers:
        - image: ghcr.io/flant/shell-operator
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            privileged: false
          name: shell-operator
          volumeMounts:
            - mountPath: "/ansible"
              name: ansible
            - mountPath: "/tmp"
              name: tmp
            - mountPath: "/var/run"
              name: var-run
            - mountPath: "/hooks/psql.sh"
              name: hooks
              subPath: psql.sh
            - mountPath: "/hooks/keycloak.sh"
              name: hooks
              subPath: keycloak.script
            - mountPath: "/templates/keycloak-oauth-proxy"
              name: hooks
              subPath: keycloak.oauth-proxy
        - image: alpine/ansible
          command:
          - sleep
          args:
          - infinity
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            privileged: false
          name: ansible
          volumeMounts:
            - mountPath: "/ansible"
              name: ansible
            - mountPath: "/tmp"
              name: tmp
---