apiVersion: v1
kind: ConfigMap
metadata:
  name: hooks
  namespace: shell-operator
data:
  psql.sh: |
    #!/bin/bash

    set -euo pipefail

    function ensure_db() {
      NAME="${1}"
      echo "Ensuring db '${NAME}' exists"

      if kubectl exec -i -n psql psql-0 -- psql -U postgres -nlqt | cut -d '|' -f 1 | grep -o -E \\S+ | grep -q -E "^${NAME}$"; then
        echo "${NAME} already exists"
      else
        echo "Creating db '${NAME}'"
        kubectl exec -i -n psql psql-0 -- psql -U postgres -c "CREATE USER ${NAME};"
        kubectl exec -i -n psql psql-0 -- psql -U postgres -c "CREATE DATABASE ${NAME} WITH OWNER ${NAME};"
      fi
    }

    if [[ ${1:-""} == "--config" ]] ; then
      cat <<EOF
    {
      "configVersion":"v1",
      "kubernetes":[
        {
          "apiVersion": "v1",
          "kind": "ConfigMap",

          "namespace": {
            "nameSelector": {
              "matchNames": ["psql"]
            }
          },
          "labelSelector": {
            "matchLabels":{
              "ongy.net/psql-db": "true"
            }
          },
          "executeHookOnEvent": ["Added"]
        }
      ]
    }
    EOF
    else
      type=$(jq -r '.[0].type' ${BINDING_CONTEXT_PATH})
      if [[ $type == "Synchronization" ]] ; then
        for db in $(jq -r '.[0].objects[]|.object.metadata.name' "${BINDING_CONTEXT_PATH}"); do
          ensure_db "${db}"
        done
      else
        if [[ "$(jq -r '.[0].watchEvent' "${BINDING_CONTEXT_PATH}")" = "Added" ]]; then
          ensure_db $(jq -r '.[0].object.metadata.name' "${BINDING_CONTEXT_PATH}")
        fi
      fi
    fi