apiVersion: v1
kind: ConfigMap
metadata:
  name: hooks
  namespace: shell-operator
data:
  psql.sh: |
    #!/bin/bash

    set -euo pipefail

    function ensure_db() {
      NAME="${1}"
      echo "Ensuring db ${NAME} exists"
    }

    if [[ ${1:-""} == "--config" ]] ; then
      cat <<EOF
    {
      "configVersion":"v1",
      "kubernetes":[
        {
          "apiVersion": "v1",
          "kind": "ConfigMap",

          "namespace": {
            "nameSelector": {
              "matchNames": ["psql"]
            }
          },
          "labelSelector": {
            "matchLabels":{
              "ongy.net/psql-db": "true"
            }
          },
          "executeHookOnEvent": ["Added"]
        }
      ]
    }
    EOF
    else
      type=$(jq -r '.[0].type' ${BINDING_CONTEXT_PATH})
      if [[ $type == "Synchronization" ]] ; then
        jq -r '.[0].objects[]|.object.metadata.name' "${BINDING_CONTEXT_PATH}"
      else
        if [[ "$(jq -r '.[0].watchEvent' "${BINDING_CONTEXT_PATH}")" = "Added" ]]; then
          ensure_db '.[0].object.metadata.name'
        fi
      fi
    fi