apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whisper
  name: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - birdo
                      - mario
      automountServiceAccountToken: false
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: whisper-config
      containers:
        - image: lscr.io/linuxserver/faster-whisper:latest
          name: faster-whisper
          volumeMounts:
            - mountPath: "/config"
              name: config
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: Etc/UTC
          - name: WHISPER_MODEL
            value: tiny-int8
---