apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
spec:
  selector:
    app: mealie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      name: http
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mealie
  namespace: default
spec:
  gateways: [istio-system/gateway]
  hosts: [mealie.local.ongy.net]
  http:
  - route:
    - destination:
        host: mealie.mealie.svc.cluster.local