apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetagger
  namespace: timetagger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timetagger
  template:
    metadata:
      labels:
        app: timetagger
    spec:
      volumes:
        - name: data
          nfs:
            path: /srv/share/backed/appdata/timetagger/
            server: mario.local.ongy.net
            readOnly: false
      containers:
        - image: ghcr.io/almarklein/timetagger:v24.07.1-nonroot
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: TIMETAGGER_BIND
              value: 0.0.0.0:8080
            - name: TIMETAGGER_DATADIR
              value: /data
            - name: TIMETAGGER_LOG_LEVEL
              value: info

            - name: TIMETAGGER_PROXY_AUTH_ENABLED
              value: "True"
            - name: TIMETAGGER_PROXY_AUTH_TRUSTED
              value: "10.0.0.0/16"
            - name: TIMETAGGER_PROXY_AUTH_HEADER
              value: x-authentik-email
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            privileged: false
          name: timetagger
          volumeMounts:
            - name: data
              mountPath: "/data"
