apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName | quote }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretValue := (get $secretData "value") | default (randAlphaNum 32 | b64enc) }}
  value: {{ $secretValue | quote }}
