apiVersion: v1
kind: ServiceAccount
metadata:
  name: jellyfin-mpv-log-reader
  namespace: jellyfin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jellyfin
  name: log-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: jellyfin-mpv-log-reader
  namespace: jellyfin
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: jellyfin-mpv-log-reader # "name" is case sensitive
  namespace: jellyfin
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: log-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io