apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-sync-argo-workflow
subjects:
- kind: ServiceAccount
  name: git-sync
roleRef:
  kind: Role
  name: argo-workflows-workflow
  apiGroup: rbac.authorization.k8s.io