apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-sync
spec:
  templates:
    - name: entry
      dag:
        tasks:
        - name: push
          template: push
    - name: push
      inputs:
        artifacts:
          - name: argo-source
            path: /src
            git:
              repo: https://git.local.ongy.net/ongy/argocd.git
              revision: main
      container:
        name: main
        volumeMounts:
        - name: github-deploy-key     # mount file containing secret at /secret/mountpath
          mountPath: "/ssh"
        env:
        - name: GIT_SSH_COMMAND
          value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /ssh/private-key"
        image: alpine/git
        command:
          - sh
        args:
          - -x
          - -euc
          - |
            ORIGIN_URL="$(git remote get-url origin)"
            GITHUB_URL="$(echo "${ORIGIN_URL}" | sed -e 's#https://git.local.ongy.net/ongy/#git@github.com:Ongy/#')"
            git remote add github "${GITHUB_URL}"
            git push github main
        workingDir: /src
  entrypoint: entry
  arguments: {}
  serviceAccountName: git-sync
  ttlStrategy:
    secondsAfterCompletion: 3600
  podGC:
    strategy: OnPodCompletion
  volumes:
  - name: github-deploy-key
    defaultMode: 400
    secret:
      secretName: github-deploy-key


