apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-sync
spec:
  arguments:
    parameters:
      - name: rev
        value: main
  templates:
    - name: entry
      dag:
        tasks:
        - name: push
          template: push
          arguments:
            parameters:
            - name: rev
              value: "{{workflow.parameters.rev}}"
    - name: push
      inputs:
        parameters:
        - name: rev
        artifacts:
          - name: argo-source
            path: /src
            git:
              repo: https://git.local.ongy.net/ongy/argocd.git
              revision: "{{inputs.parameters.rev}}"
      container:
        name: main
        volumeMounts:
        - name: github-deploy-key     # mount file containing secret at /secret/mountpath
          mountPath: "/ssh"
          readOnly: true
        env:
        - name: GIT_SSH_COMMAND
          value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /ssh/private-key"
        image: alpine/git
        command:
          - sh
        args:
          - -x
          - -euc
          - |
            ORIGIN_URL="$(git remote get-url origin)"
            GITHUB_URL="$(echo "${ORIGIN_URL}" | sed -e 's#https://git.local.ongy.net/ongy/#git@github.com:Ongy/#')"
            git remote add github "${GITHUB_URL}"
            git push github main
        workingDir: /src
  entrypoint: entry
  serviceAccountName: git-sync
  ttlStrategy:
    secondsAfterCompletion: 3600
  podGC:
    strategy: OnPodCompletion
  volumes:
  - name: github-deploy-key
    secret:
      defaultMode: 256 # 0400
      secretName: github-deploy-key


