apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anki-sync-server
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: anki-sync-server
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mediaserver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
