apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: argo-workflows
    targetRevision: main
  - chart: argo-events
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.4.4
    helm:
      releaseName: argo-events
  - chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.45.2
    helm:
      valuesObject:
        workflow:
          serviceAccount:
            create: true
        artifactRepository:
          s3:
            accessKeySecret:
              name: argo-artifacts
              key: AWS_ACCESS_KEY_ID
            secretKeySecret:
              name: argo-artifacts
              key: AWS_SECRET_ACCESS_KEY
            insecure: true
            bucket: argo-workflow-artifacts-307d87ae-0425-41d3-a389-fd9ec5ac8790
            endpoint: rook-ceph-rgw-my-store.rook-ceph.svc:80
        server:
          authModes:
          - sso
          sso:
            clientId:
              name: keycloak-client-argo-workflows
              key: client_id
            clientSecret:
              name: keycloak-client-argo-workflows
              key: client_secret
            enabled: true
            issuer: https://keycloak.local.ongy.net/realms/local.ongy.net
            redirectUrl: https://argo-workflows.local.ongy.net/oauth2/callback
            rbac:
              enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true