apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-event-aggregator
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: argo-workflows-event-aggregator
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
