apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.45.2
    helm:
      valuesObject:
        server:
          sso:
            enabled: true
            issuer: https://keycloak.local.ongy.net/realms/local.ongy.net
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true

