apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.45.2
    helm:
      valuesObject:
        artifactRepository:
          s3:
            accessKeySecret:
              name: argo-artifacts
              key: AWS_ACCESS_KEY_ID
            secretKeySecret:
              name: argo-artifacts
              key: AWS_SECRET_ACCESS_KEY
            insecure: true
            bucket: argo-workflow-artifacts-307d87ae-0425-41d3-a389-fd9ec5ac8790
            endpoint: rook-ceph-rgw-my-store.rook-ceph.svc:80
        server:
          authModes:
          - sso
          sso:
            enabled: true
            issuer: https://keycloak.local.ongy.net/realms/local.ongy.net
            redirectUrl: https://argo-workflows.local.ongy.net/oauth2/callback
            rbac:
              enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-server-sso
  namespace: argo-workflows
data:
  client-secret: SWxXOHI4Qkg4RXE1eDRMY0RqaWhjVGdyVlBtYlBVQVo=
  client-id: YXJnby13b3JrZmxvd3M=
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  hostnames:
  - argo-workflows.local.ongy.net
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
    namespace: kube-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: argo-workflows-server
      port: 2746
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: argo-artifacts
  namespace: argo-workflows
spec:
  generateBucketName: argo-workflow-artifacts
  storageClassName: rook-ceph-bucket


