apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-iii
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - chart: importer
    repoURL: https://firefly-iii.github.io/kubernetes/
    targetRevision: 1.5.1
    helm:
      valuesObject:
            
        fireflyiii:
          url: http://firefly-iii:80
          vanityUrl: https://firefly.local.ongy.net
          auth:
            accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjIzNmVjMjc5NWYxNDhiMWM5ODJhM2JmYmJiNmRkNGJmZjkwNjEwMzRmMjM4ZWYxMWY1OWIyZGI3NzA1NzdmZTVlMDJjNDZjMDBhNGE0ZWYiLCJpYXQiOjE3NzUyODQxMzEuNzg3MzgzLCJuYmYiOjE3NzUyODQxMzEuNzg3NDI4LCJleHAiOjE4MDY4MjAxMzEuNjE0ODk1LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.TlJq4jNp5Wu1Er6yIU1HvWuCr26-R3y_1yeKpajL_vhBF7IxWodwo7n9_HNOg9m_w_AcGE-FakeVjVuvlTUixkEc4Mw83KtCLaAvwpzxMi268Cbz4Asbhm7PY2FBiVm1EwCgjcE5Q4wXjd7RX5CQECkNuGnfrbxjaj9sI-_kV1do1U0mEUcxQUNHIzJAJlmU5ivE0wqjjhg_1hHTNPqrFTPgQ236qee60LKcYQz--8KNNV9if6_3ExqpANjxRClTSgBlKAyKW5g9sG3SE14cfWUPdqohOuqsTSjkviVe1rUAonh2ag3nGQZf1iOpkjFc2F0W40RDVl7ojBZaNsmhkBn3VlV5nftVZQtWwTPesZ0uFBisB4f6scBPJwmNx1E1Q6kUsCIOX8defE6_MH4njD4hhxCbWK4z0kEQL1lrFskwIqv7THrzG-QSn-91XBsKLshAHYgtruGHaLqYTCnuf3arngesIwEJfoOYDRo6oQKiHKOBhgDaW2E9nPrxQ502uMUOmVPdhgd30L2u280fFGe2xtfGbPr6jhSUvTq6wTD2Rv6iqyU3i1Y4dK8SOlyyja9tKqGPrn8wp-XSzqo6gC0VdjGpPJtbCxyllWMViN2M3WV6B4F96Vz7k4ms43ziVTpIVLJEnqhgSgn0dcU9MzCV1nG_CiWo3fT23eNmG2A
  - chart: firefly-iii
    repoURL: https://firefly-iii.github.io/kubernetes/
    targetRevision: 1.9.12
    helm:
      valuesObject:
        podSecurityContext:
          fsGroup: 33
          fsGroupChangePolicy: "OnRootMismatch"
        extraVolumes:
        - name: psql-tls-secrets
          secret:
            defaultMode: 416
            secretName: psql-client-secret
        extraVolumeMounts:
        - mountPath: "/psql-tls-secrets"
          name: psql-tls-secrets
        persistence:
          storageClassName: "rook-cephfs"
        config:
          env:
            "DB_CONNECTION": "pgsql"
            "DB_DATABASE": "firefly"
            "DB_HOST": psql.psql
            "DB_PORT": "5432"
            "DB_USERNAME": "firefly"
            
            "PGSQL_SSL_MODE": "verify-full"
            "PGSQL_SSL_CERT": "/psql-tls-secrets/..data/tls.crt"
            "PGSQL_SSL_KEY": "/psql-tls-secrets/..data/tls.key"
            "PGSQL_SSL_ROOT_CERT": "/psql-tls-secrets/..data/ca.crt"

            "DEFAULT_LANGUAGE": "en_US"
            "DEFAULT_LOCALE": "equal"
            "TRUSTED_PROXIES": "**"
            "TZ": "Europe/Berlin"	

            AUTHENTICATION_GUARD: remote_user_guard
            AUTHENTICATION_GUARD_HEADER: X-Forwarded-User
            AUTHENTICATION_GUARD_EMAIL: X-Forwarded-Email
  - repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: firefly-iii
    targetRevision: main
  - repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: secret-value
    targetRevision: main
    helm:
      valuesObject:
        secretName: firefly-oauth-cookie
  destination:
    server: "https://kubernetes.default.svc"
    namespace: firefly
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ServerSideApply=true


