apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ha=ghcr.io/home-assistant/home-assistant
    argocd-image-updater.argoproj.io/ha.update-strategy: newest-build
    argocd-image-updater.argoproj.io/ha.allow-tags: 'regexp:2024\.7\.[2-9]'
    argocd-image-updater.argoproj.io/ha.platforms: linux/amd64
spec:
  project: default
  source:
    repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: homeassistant
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homeassistant
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
