apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: mpv-shim=cr.local.ongy.net/jellyfin-mpv-shim,jellyfin=jellyfin/jellyfin:>10.10
    argocd-image-updater.argoproj.io/jellyfin.update-strategy: semver
    argocd-image-updater.argoproj.io/mpv-shim.update-strategy: newest-build
    argocd-image-updater.argoproj.io/mpv-shim.allow-tags: any
    argocd-image-updater.argoproj.io/jellyfin.allow-tags: regexp:^[0-9]+\.[0-0]+\.[0-9]+$
spec:
  project: default
  source:
    repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: jellyfin
    targetRevision: new-cluster
    kustomize:
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
