apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: mealie=ghcr.io/mealie-recipes/mealie
    argocd-image-updater.argoproj.io/homeassistant.update-strategy: newest-build
    argocd-image-updater.argoproj.io/homeassistant.allow-tags: regexpv:^[0-9]+\.[0-9]+\.[1-9][0-9]*$

    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-repository: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    argocd-image-updater.argoproj.io/write-back-target: kustomization:/mealie
spec:
  project: default
  sources:
  - repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: mealie
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mealie
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
