apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
#    argocd-image-updater.argoproj.io/image-list: ha=ghcr.io/flant/shell-operator
#    argocd-image-updater.argoproj.io/ha.update-strategy: newest-build
    # argocd-image-updater.argoproj.io/ha.allow-tags: 'regexp:2024\.7\.[2-9]'
    # argocd-image-updater.argoproj.io/ha.platforms: linux/amd64
spec:
  project: default
  source:
    repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: mongodb
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
