apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-assistant
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: musicassistant
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: smarthome
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
