apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: paperless=ghcr.io/paperless-ngx/paperless-ngx
    argocd-image-updater.argoproj.io/paperless.update-strategy: semver
    argocd-image-updater.argoproj.io/paperless.allow-tags: regexp:^[0-9]+\.[0-9]+\.[1-9][0-9]*$
spec:
  project: default
  sources:
  - repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: paperless
    targetRevision: main
  - repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: secret-value
    targetRevision: main
    helm:
      valuesObject:
        secretName: paperless-oauth-cookie
#  - repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
#    path: snapshot-schedule
#    targetRevision: main
#    helm:
#      valuesObject:
#        suffix: paperless
#        appSelector: paperless
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mediaserver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
