apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: paperless=ghcr.io/paperless-ngx/paperless-ngx
    argocd-image-updater.argoproj.io/paperless.update-strategy: semver
    argocd-image-updater.argoproj.io/paperless.allow-tags: regexp:^[0-9]+\.[0-9]+\.[1-9][0-9]*$
spec:
  project: default
  source:
    repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: paperless
    targetRevision: new-cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mediaserver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
