apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: photoprism=photoprism/photoprism
    argocd-image-updater.argoproj.io/photoprism.update-strategy: newest-build
    argocd-image-updater.argoproj.io/photoprism.allow-tags: 'regexp:24[0-1][0-9][0-3][0-9]'
spec:
  project: default
  source:
    repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: photoprism
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mediaserver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
