apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: photoprism/photoprism
    argocd-image-updater.argoproj.io/photoprism/photoprism.update-strategy: latest
    argocd-image-updater.argoproj.io/photoprism/photoprism.allow-tags: '24\d{4}'
spec:
  project: default
  source:
    repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: photoprism
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mediaserver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
