apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: photoprism=photoprism/photoprism
    argocd-image-updater.argoproj.io/photoprism.update-strategy: newest-build
    argocd-image-updater.argoproj.io/photoprism.allow-tags: regexp:^[0-9]+$
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: photoprism
    targetRevision: new-cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mediaserver
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
