apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.3.1
    helm:
      valuesObject:
        grafana:
          enabled: false
        alertmanager:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ServerSideApply=true


