apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
  - chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.3.1
    helm:
      valuesObject:
        grafana:
          enabled: false
        alertmanager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeControllerManager:
          enabled: false
  - repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: prometheus
    targetRevision: main
  - repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: secret-value
    targetRevision: main
    helm:
      valuesObject:
        secretName: prometheus-oauth-cookie
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-prometheus
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ServerSideApply=true


