apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psql
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: psql
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: psql
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
