apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: radarr
    targetRevision: main
  - repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: secret-value
    targetRevision: main
    helm:
      valuesObject:
        secretName: radarr-oauth-cookie
  - repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: snapshot-schedule
    targetRevision: main
    helm:
      valuesObject:
        suffix: radarr
        subhourly: false
        appSelector: radarr
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mediaretriever
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
