apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shapshot-scheduler
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
#  - repoURL: https://git.local.ongy.net/ongy/argocd.git
#    path: shapshot-scheduler
#    targetRevision: new-cluster
  - chart: snapscheduler
    repoURL: https://backube.github.io/helm-charts/
    targetRevision: 3.4.0
    helm:
      valuesObject:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backube-snapscheduler
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true