apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: sonarr
    targetRevision: new-cluster
  - repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: secret-value
    targetRevision: new-cluster
    helm:
      valuesObject:
        secretName: sonarr-oauth-cookie
  - repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: snapshot-schedule
    targetRevision: new-cluster
    helm:
      valuesObject:
        suffix: sonarr
        subhourly: false
        claimSelector: app.kubernetes.io/instance=sonarr
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mediaretriever
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
