apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
  # The default behaviour is foreground cascading deletion
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://git.local.ongy.net/ongy/argocd.git
    path: vaultwarden
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: experiments
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
