apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: z2m=koenkk/zigbee2mqtt
    argocd-image-updater.argoproj.io/z2m.update-strategy: semver
    argocd-image-updater.argoproj.io/z2m.allow-tags: regexp:^[0-9]+\.[0-9]+\.[1-9][0-9]*$
spec:
  project: default
  source:
    repoURL: ssh://git@git.local.ongy.net:7022/ongy/argocd.git
    path: z2m
    targetRevision: new-cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: smarthome
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
