apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: photoprism
  name: photoprism
  namespace: mediaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoprism
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: photoprism-config
          persistentVolumeClaim:
            claimName: photoprism-config-pvc
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 150Mi
        - name: run
          emptyDir:
            medium: Memory
            sizeLimit: 100Mi
      initContainers:
        - image: alpine
          command:
          - chown
          - -R
          - 1001:1001
          - /run
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
              add: ['NET_BIND_SERVICE']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
          name: set-mount-privs
          volumeMounts:
            - mountPath: "/run"
              name: run
      containers:
        - image: photoprism/photoprism
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
              add: ['NET_BIND_SERVICE']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            privileged: false
          readinessProbe:
            httpGet:
              path: /
              port: 2342
          env:
            - name: PHOTOPRISM_UPLOAD_NSFW
              value: "true"
            - name: PHOTOPRISM_ADMIN_PASSWORD
              value: "insecure"
            - name: PHOTOPRISM_SPONSOR
              value: "true"
            - name: PHOTOPRISM_ORIGINALS_LIMIT
              value: "-1"
          name: photoprism
          volumeMounts:
            - mountPath: "/photoprism"
              name: photoprism-config
            - mountPath: "/tmp"
              name: tmp
            - mountPath: "/run"
              name: run
