apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  labels:
    name: external-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.2
        args:
        - --registry=txt
        - --txt-prefix=external-dns-
        - --txt-owner-id=k8s
        - --provider=rfc2136
        - --rfc2136-host=192.168.128.1
        - --rfc2136-port=5300
        - --rfc2136-zone=local.ongy.net
        - --rfc2136-insecure
        - --rfc2136-tsig-axfr
        - --source=istio-gateway        # choose one
        - --source=istio-virtualservice # or both
        - --domain-filter=local.ongy.net
