apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: hugo-build
spec:
  template:
    serviceAccountName: argo-workflows-server
  dependencies:
    - name: webhook-dep
      eventSourceName: hugo-build-webhook
      eventName: hugo-build-webhook
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: hugo-build-
              spec:
                arguments:
                  parameters:
                  - name: rev
                    value: __TO_BE_REPLACD__
                  - name: repo
                    value: __TO_BE_REPLACD__
                workflowTemplateRef:
                  name: hugo-build
          parameters:
            - src:
                dependencyName: webhook-dep
                dataKey: body.ref
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: webhook-dep
                dataKey: body.repository.clone_url
              dest: spec.arguments.parameters.1.value
