apiVersion: v1
kind: ServiceAccount
metadata:
  name: hugo-build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hugo-build-argo-workflow
subjects:
- kind: ServiceAccount
  name: hugo-build
roleRef:
  kind: Role
  name: argo-workflows-workflow
  apiGroup: rbac.authorization.k8s.io