apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: music-assistant
  template:
    metadata:
      labels:
        app: music-assistant
    spec:
      hostNetwork: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: music-assistant-config
      containers:
      - image: ghcr.io/music-assistant/server
        name: assistant
        volumeMounts:
        - name: data
          mountPath: /data
        ports:
        - name: http
          protocol: TCP
          containerPort: 8095
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        readinessProbe:
          httpGet:
            path: /
            port: http