apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-config
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
