apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
  namespace: smarthome
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      volumes:
        - name: zigbee2mqtt-data
          persistentVolumeClaim:
            claimName: zigbee2mqtt
      containers:
        - image: koenkk/zigbee2mqtt
          imagePullPolicy: IfNotPresent
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - cap_chown
              - cap_dac_override
              - cap_fowner
              - cap_fsetid
              - cap_kill
              - cap_setgid
              - cap_setuid
              - cap_setpcap
              # - cap_net_bind_service Not dropped due to setcap on node file.
              - cap_net_raw
              - cap_sys_chroot
              - cap_mknod
              - cap_audit_write
              - cap_setfcap
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 998
            runAsGroup: 20
            privileged: false
            readOnlyRootFilesystem: true
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          env:
            - name: TZ
              value: Europe/Amsterdam
          name: zigbee2mqtt
          volumeMounts:
            - mountPath: "/app/data"
              name: zigbee2mqtt-data
          resources:
            requests:
              memory: 256Mi
              cpu: "500m"
              ongy.net/zigbee: 1
            limits:
              memory: 256Mi
              cpu: "500m"
              ongy.net/zigbee: 1