apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
  namespace: smarthome
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      volumes:
        - name: zigbee2mqtt-data
          persistentVolumeClaim:
            claimName: zigbee-pvc
      containers:
        - image: koenkk/zigbee2mqtt:1.36.1 # {"$imagepolicy": "flux-system:zigbee2mqtt"}
          imagePullPolicy: IfNotPresent
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 998
            runAsGroup: 20
            privileged: false
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          env:
            - name: TZ
              value: Europe/Amsterdam
          name: zigbee2mqtt
          volumeMounts:
            - mountPath: "/app/data"
              name: zigbee2mqtt-data
          resources:
            requests:
              memory: 256Mi
              cpu: "500m"
              ongy.net/zigbee: 1
            limits:
              memory: 256Mi
              cpu: "500m"
              ongy.net/zigbee: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: z2m-storage-migration
spec:
  template:
    spec:
      containers:
      - name: copy
        image: alpine
        command:
        - sh
        - -c
        - tar -cC /nfs --numeric-owner . | tar -xC /ceph --numeric-owner
        volumeMounts:
          - mountPath: "/nfs"
            name: nfs
          - mountPath: "/ceph"
            name: ceph
      volumes:
        - name: nfs
          nfs:
            path: /srv/share/backed/appdata/zigbee2mqtt/
            server: mario.local.ongy.net
            readOnly: false
        - name: ceph
          persistentVolumeClaim:
            claimName: zigbee2mqtt
      restartPolicy: Never
